#!/usr/bin/env perl

use strict;
use warnings;

my $i = 0;
my @p;
while (<>) {
    chomp;
    if (/^(\d+)\s+(.+)$/) {
        my ($n, $label) = ($1, $2);

        while ($i++ < $n) {
            push @p, "Reserved";
        }

        push @p, $label;
    }
}

for (my $j = 0; $j < @p; $j++) {
    print qq|"$p[$j]", |;
    if ($j % 5 == 0) {
        print "// $j\n";
    }
}

#    chomp;
#    if (/^(\d+)\s+([^\(]+)(\((.+?)\))?/) {
#        my ($i, $name, $shortened) = ($1, $2, $4);
#        $name =~ s/[^A-Za-z0-9]//g;
#
#        print "    $name = $i\n";
#        if (defined $shortened && $shortened ne "") {
#            $shortened =~ s/[^A-Za-z0-9]//g;
#            print "    $shortened = $i\n";
#        }
#    }
#}
